### ISSUE TITLE
To provide other parameters

### ISSUE THREAD

**Issue by iyogeshjoshi** [pdeschen/bancroft#15]
I'm using your module from long time now. It's really good and helpful thank you :smile: .
I need some extra parameters like ept, mode, epx, epv. I'm gettting them with the location data, I think you're filtering it out. Is it possible to add those parameters to the json object?

**Comment by pdeschen** [comment]
I'm glad you find it helpful. Do you mind sharing your device brand and model?

I'll bump the version and push over npm shortly.

**Comment by iyogeshjoshi** [comment]
@pdeschen I'm using using Ublox's GSM and GPS module :smile:
