### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by 0xceb1d** [pdeschen/bancroft#8]
I have tried to run your example with a ND-100S GPS receiver, it displays 'connected' in the console however it does not show up message regarding location or satellites.

I have installed GPSD however it returns the following for the 'test':

```
$ sudo apt-get install gpsd
$ sudo gpsd -D 2 -n -b -N -P /tmp/gpsd.pid /dev/ttyUSB0
```

```
gpsd:INFO: launching (Version 3.6)
gpsd:ERROR: can't bind to IPv4 port gpsd, Address already in use
gpsd:ERROR: maybe gpsd is already running!
gpsd:ERROR: can't create IPv6 socket
```

The second test fails as well:

```
$ gpspipe -w
```

```
-bash: gpspipe: command not found
```

When running the app this is the output:

```
pi@raspberrypi ~/Desktop/pi $ sudo nodejs app.js
The "sys" module is now called "util". It should have a similar interface.
connected
```

**Comment by Decontra** [comment]
I have Kali Linux 2.0 running within VirtualBox and I'm trying to run Kismet with my gps receiver (BU-353S4). However, I am running into the same issue with gpsd already running when entering the command gpsd -D 2 -N /dev/ttyUSB0 into the terminal. 

gpsd:ERROR: can't bind to IPv4 port gpsd, Address already in use
gpsd:ERROR: maybe gpsd is already running!
gpsd:ERROR: can't bind to IPv6 port gpsd, Address already in use
gpsd:ERROR: maybe gpsd is already running!

I have tried entering: 

sudo killall gpsd
sudo service gpsd start

But have had no luck. Any help with this would be really appreciated.

**Comment by Zuendelmeister** [comment]
Same problem here with a ND-100S.

> sudo gpsd -D 4 -N /dev/ttyUSB0
gpsd:INFO: launching (Version 3.11)
gpsd:ERROR: can't bind to IPv4 port gpsd, Address already in use
gpsd:ERROR: maybe gpsd is already running!
gpsd:ERROR: can't bind to IPv6 port gpsd, Address already in use
gpsd:ERROR: maybe gpsd is already running!
gpsd:INFO: command sockets creation failed, netlib errors -1, -1

And using cat doesn't work ether:
> stty -F /dev/ttyUSB0 4800
> sudo cat /dev/ttyUSB0
0
 ������l�m
              p�������)l�m�����		
                                                                -�`z����l�mt���9�CDܰ���[)l�F��
	p����*����
                      X�����l�m{
                                   p�������)^C%              

The killall command didn't help as well, since there was no gpsd started.

**Comment by pdeschen** [comment]
@Zuendelmeister if you can't get gpsd to work, bancroft won't work since it is merely a client to that daemon. I would suggest you hop over [gpsd mailing list](http://www.catb.org/gpsd/#mailing-lists) for some help.
